The first part of the code involves seperation of values from dataset which can not be done woithout imported libraries. The data set I chose was IRIS.

In [2]:
from google.colab import files

uploaded = files.upload()



Saving iris.data to iris.data


In [11]:
import pandas as pd

df = pd.read_csv('iris.data')

print(df.describe())

x = df.iloc[:, :-1]   #all columns except last
y = df.iloc[:, -1]    #only last column



              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000


In [22]:
import numpy as np

train_size = int(len(x) * 0.6)    #60 40 training testing ratio

#shuffle to get data of all types
indices = np.arange(len(x))
np.random.shuffle(indices)

#access X according to shuffled indices
x_train = x.iloc[indices[:train_size], :]
y_train = y.iloc[indices[:train_size]]
x_test = x.iloc[indices[train_size:], :]
y_test = y.iloc[indices[train_size:]]



#mapping labels to integers
unique_classes = np.unique(y_train)
label_map = {class_label: idx for idx, class_label in enumerate(unique_classes)}
y_train_mapped = np.array([label_map[label] for label in y_train])
x_train_mapped = np.array(x_train)
print(x_train_mapped)

[[5.9 3.2 4.8 1.8]
 [5.8 2.6 4.  1.2]
 [6.  2.2 5.  1.5]
 [5.1 2.5 3.  1.1]
 [6.4 2.7 5.3 1.9]
 [5.4 3.7 1.5 0.2]
 [4.8 3.1 1.6 0.2]
 [6.1 2.6 5.6 1.4]
 [5.8 2.7 5.1 1.9]
 [6.3 2.5 4.9 1.5]
 [5.5 3.5 1.3 0.2]
 [6.8 3.2 5.9 2.3]
 [6.  3.4 4.5 1.6]
 [6.4 3.2 5.3 2.3]
 [5.6 3.  4.1 1.3]
 [6.3 3.3 6.  2.5]
 [4.6 3.6 1.  0.2]
 [6.1 2.9 4.7 1.4]
 [6.  3.  4.8 1.8]
 [5.  3.2 1.2 0.2]
 [6.3 2.9 5.6 1.8]
 [6.4 3.2 4.5 1.5]
 [4.7 3.2 1.6 0.2]
 [6.  2.2 4.  1. ]
 [7.7 3.  6.1 2.3]
 [5.7 2.8 4.5 1.3]
 [7.4 2.8 6.1 1.9]
 [5.6 2.5 3.9 1.1]
 [5.6 2.7 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [6.4 2.8 5.6 2.1]
 [6.7 3.1 5.6 2.4]
 [5.2 3.4 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [4.4 3.  1.3 0.2]
 [5.9 3.  4.2 1.5]
 [5.1 3.8 1.9 0.4]
 [5.4 3.9 1.7 0.4]
 [5.7 2.6 3.5 1. ]
 [6.4 3.1 5.5 1.8]
 [6.4 2.9 4.3 1.3]
 [4.8 3.4 1.9 0.2]
 [6.7 3.3 5.7 2.1]
 [5.5 2.6 4.4 1.2]
 [5.8 2.7 4.1 1. ]
 [7.2 3.  5.8 1.6]
 [6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [6.3 3.3 4.7 1.6]
 [6.7 3.  5.  1.7]
 [6.2 2.8 4.

This part of the code implements the MLP and was done without any external libraries.

In [57]:
import random

class perceptron:

  def __init__(self, input_size,learning_rate):
    self.bias = 1    #start with bias as 1
    self.output = 0
    self.weights =[random.uniform(-1, 1) for _ in range(input_size)]    #random weights for previous inputs
    self.learning_rate = learning_rate

  def sigmoid(self,x):
    return 1 / (1 + pow(2.71828, -x))

  def multiply_arrays(self, inputs, weights):
    result = 0
    for i in range(len(inputs)):
        result += inputs[i] * weights[i]
    return result

  def forwardpass(self,inputs):
    self.inputs = inputs
    value = self.multiply_arrays(inputs, self.weights) + self.bias
    #activation function
    self.output = self.sigmoid(value)
    return self.output

  def backprop(self,error ):
    #calculate
    delta_error = error * self.output * (1 - self.output)
    delta_weight = self.inputs
    delta_bias = 1
    #Update weights and bias
    for i in range(0,len(self.weights)):
      self.weights[i] += self.learning_rate * delta_error * delta_weight[i]
    self.bias += self.learning_rate * delta_error * delta_bias






class MLP:

  def __init__(self, input_layer_size, hidden_layer_size, output_layer_size,learning_rate = 0.02):
    self.input_layer_size = input_layer_size
    self. hidden_layer_size = hidden_layer_size
    self.output_layer_size = output_layer_size
    self.learning_rate = learning_rate
    self.hidden_layer = []
    self.output_layer = []

    for i in range(0,hidden_layer_size):
      p = perceptron(input_layer_size,learning_rate)
      self.hidden_layer.append(p)

    for i in range(0,output_layer_size):
      p = perceptron(hidden_layer_size,learning_rate)
      self.output_layer.append(p)


  def train(self,max_iters,targets,inputs):
    for j in range(0,max_iters):
      # forward pass
      output = []
      input2output_layer = []
      for p in self.hidden_layer:
        input2output_layer.append(p.forwardpass(inputs[j]))
      for p in self.output_layer:
        output.append(p.forwardpass(input2output_layer))
      label = output.index(max(output))

      #error calc
      error = targets[j] - label
      for p in self.output_layer:
        p.backprop(error)
      for p in self.hidden_layer:
        p.backprop(error)



  def predict(self, inputs):

    output = []
    input2output_layer = []
    for p in self.hidden_layer:
      input2output_layer.append(p.forwardpass(inputs))
    for p in self.output_layer:
      output.append(p.forwardpass(input2output_layer))

    maximum = output.index(max(output))

    if maximum ==  0:
      print("Iris-setosa")
    elif maximum == 1:
      print("Iris-versicolor")
    elif maximum == 2:
      print("Iris-virginica")
    return maximum




#-----------------------------------------------------------------------------MAIN-------------------------------------------------------------
mlp =  MLP(4,4,3,0.02)
mlp.train(len(x_train_mapped),y_train_mapped,x_train_mapped)

print(mlp.predict((4.9,3.1,1.5,0.1)))


Iris-versicolor
1


Now to evaluate data based on accuracy. Based on the output the MLP is giving 48% accuracy as of now.

In [62]:
unique_classes = np.unique(y_test)
label_map = {class_label: idx for idx, class_label in enumerate(unique_classes)}
y_test_mapped = np.array([label_map[label] for label in y_test])
x_test_mapped = np.array(x_test)

print(y_test_mapped)


predict = []
for x in range(len(x_test_mapped)):
  predict.append(mlp.predict(x_test_mapped[x]))

sum = 0
for i in range(len(x_test_mapped)):
  if predict[i] == y_test_mapped[i]:
    sum += 1

# Calculate accuracy
correct_predictions = sum
total_instances = len(y_test_mapped)
accuracy = correct_predictions / total_instances
print("Accuracy:", accuracy)






[2 1 0 0 2 2 1 2 1 2 2 1 2 1 0 1 0 2 1 0 1 1 2 1 0 2 2 2 0 0 1 0 0 1 1 2 1
 1 2 1 2 1 0 1 0 2 1 2 0 0 1 0 2 0 1 2 2 0 1 0]
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-virginica
Iris-virginica
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-virginica
Iris-versicolor
Iris-virginica
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-virginica
Iris-versicolor
Iris-versicolor
Iris-virginica
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iri